//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP.NET_MVC_A_CRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public int Department_Id { get; set; }
        public string Department_Name { get; set; }
    }
}
